spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:mysql}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:security}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

  jackson:
    property-naming-strategy: SNAKE_CASE

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

server:
  port: 8080

exchange:
  server:
    jar-path: ${EXCHANGE_SERVER_JAR_PATH:exchange/build/libs/exchange-0.0.1-SNAPSHOT.jar}
    host: ${EXCHANGE_SERVER_HOST:exchange-server}
    port: ${EXCHANGE_SERVER_PORT:8081}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expired-at: ${ACCESS_TOKEN_EXPIRED_AT:999999}
  refresh-token-expired-at: ${REFRESH_TOKEN_EXPIRED_AT:7}

aes:
  secret-key: ${AES_SECRET_KEY}
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE