spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB_NAME:security}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 8080

exchange-server:
  host: ${EXCHANGE_SERVER_HOST:localhost}
  port: ${EXCHANGE_SERVER_PORT:8081}